# Generated by Django 4.2.3 on 2023-08-23 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listado_dispositivos_medicos', '0001_initial'),
        ('matriz_dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePriorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorizacion', models.BooleanField(default=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado_dispositivos_medicos.listadodispositivosmedicos')),
            ],
        ),
        migrations.CreateModel(
            name='Priorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_priorizacion', models.DateTimeField(auto_now=True)),
                ('matriz_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorizaciones', to='matriz_dispositivos.matrizdispositivos')),
                ('pre_priorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorizaciones', to='priorizacion.prepriorizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Preseleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dispositivos', models.ManyToManyField(to='listado_dispositivos_medicos.listadodispositivosmedicos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prepriorizacion',
            name='preseleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorizacion.preseleccion'),
        ),
    ]
