# Generated by Django 4.2.3 on 2023-08-23 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('priorizacion', '0002_prepriorizacion_modify_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepriorizacion',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='preseleccion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='priorizacion',
            name='fecha_priorizacion',
        ),
        migrations.AddField(
            model_name='prepriorizacion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preseleccion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priorizacion',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
